#!/usr/bin/env bash
set -euo pipefail

GTVPN_ROOT="${GTVPN_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
# shellcheck source=/dev/null
source "$GTVPN_ROOT/lib/common.sh"
load_config

REAL_VPNC_SCRIPT="$DEFAULT_VPNC_SCRIPT"
LOG_FILE="$ROUTE_LOG"

log_msg() {
  printf '[%s] [%s] %s\n' "$(/bin/date '+%Y-%m-%d %H:%M:%S')" "${reason:-unknown}" "$*" >> "$LOG_FILE"
}

ensure_vpnc_resolv_backup() {
  local backup
  [[ -z "${VPNPID:-}" ]] && return
  backup="/var/run/vpnc/resolv.conf-backup.${VPNPID}"

  if [[ ! -f "$backup" ]] && /usr/bin/grep -q '^#@VPNC_GENERATED@' /etc/resolv.conf 2>/dev/null; then
    /bin/cp -f /var/run/resolv.conf "$backup" 2>/dev/null || true
    /bin/chmod 644 "$backup" 2>/dev/null || true
    log_msg "Created missing vpnc resolv backup $backup"
  fi
}

normalize_resolv_conf() {
  local nameserver search_domain
  nameserver="$(/usr/sbin/scutil --dns 2>/dev/null | /usr/bin/awk '
    /nameserver\[[0-9]+\] :/ {
      if ($3 !~ /^130\.207\./) { print $3; exit }
    }')"
  search_domain="$(/usr/sbin/scutil --dns 2>/dev/null | /usr/bin/awk '
    /search domain\[[0-9]+\] :/ {
      if ($4 !~ /gatech\.edu$/) { print $4; exit }
    }')"

  [[ -z "$nameserver" ]] && nameserver="$LOCAL_DNS_FALLBACK"

  {
    printf '# macOS Notice\n'
    printf '# This file is automatically generated.\n'
    [[ -n "$search_domain" ]] && printf 'search %s\n' "$search_domain"
    printf 'nameserver %s\n' "$nameserver"
  } > /var/run/resolv.conf

  log_msg "Normalized /var/run/resolv.conf (nameserver=$nameserver search=${search_domain:-none})"
}

service_for_interface() {
  local ifname="$1"
  /usr/sbin/networksetup -listnetworkserviceorder 2>/dev/null | /usr/bin/awk -v dev="$ifname" '
    /^\([0-9]+\)/ {
      service=$0
      sub(/^\([0-9]+\)[[:space:]]*/, "", service)
      sub(/^\*[[:space:]]*/, "", service)
    }
    $0 ~ ("Device: " dev "\\)") {
      print service
      exit
    }
  '
}

restore_primary_dns_to_dhcp() {
  local default_if service
  default_if="$(/sbin/route -n get default 2>/dev/null | /usr/bin/awk '/interface:/{print $2; exit}')"
  [[ -z "$default_if" ]] && return
  service="$(service_for_interface "$default_if")"
  [[ -z "$service" ]] && return

  /usr/sbin/networksetup -setdnsservers "$service" Empty >/dev/null 2>&1 || true
  /usr/sbin/networksetup -setsearchdomains "$service" Empty >/dev/null 2>&1 || true
  log_msg "Restored DHCP DNS on $service ($default_if)"
}

add_gt_routes() {
  local gw dns route net prefix mask
  gw="${INTERNAL_IP4_ADDRESS:-}"
  [[ -z "$gw" ]] && return

  for dns in $GT_DNS_HOSTS; do
    /sbin/route -n delete -host "$dns" >/dev/null 2>&1 || true
    /sbin/route -n add -host "$dns" "$gw" >/dev/null 2>&1 || true
  done

  for route in $GT_NET_ROUTES; do
    net="$(cidr_net "$route")"
    prefix="$(cidr_prefix "$route")"
    mask="$(cidr_to_mask "$prefix")"
    /sbin/route -n delete -net "$net" -netmask "$mask" >/dev/null 2>&1 || true
    /sbin/route -n add -net "$net" -netmask "$mask" "$gw" >/dev/null 2>&1 || true
  done

  log_msg "Applied GT host/net routes via $gw"
}

remove_gt_routes() {
  local dns route net prefix mask

  for dns in $GT_DNS_HOSTS; do
    /sbin/route -n delete -host "$dns" >/dev/null 2>&1 || true
  done

  for route in $GT_NET_ROUTES; do
    net="$(cidr_net "$route")"
    prefix="$(cidr_prefix "$route")"
    mask="$(cidr_to_mask "$prefix")"
    /sbin/route -n delete -net "$net" -netmask "$mask" >/dev/null 2>&1 || true
  done

  log_msg "Removed GT host/net routes"
}

remove_tunnel_default_routes() {
  local tun gw removed4 removed6
  tun="${TUNDEV:-}"
  [[ -z "$tun" ]] && return
  removed4=0
  removed6=0

  while :; do
    gw="$(/usr/sbin/netstat -rn -f inet 2>/dev/null | /usr/bin/awk -v t="$tun" '$1 == "default" && $4 == t { print $2; exit }')"
    [[ -z "$gw" ]] && break
    if [[ "$gw" == link#* ]]; then
      /sbin/route -n delete default -ifscope "$tun" >/dev/null 2>&1 || break
    else
      /sbin/route -n delete default "$gw" >/dev/null 2>&1 || break
    fi
    removed4=$((removed4 + 1))
  done

  while :; do
    gw="$(/usr/sbin/netstat -rn -f inet6 2>/dev/null | /usr/bin/awk -v t="$tun" '$1 == "default" && $4 == t { print $2; exit }')"
    [[ -z "$gw" ]] && break
    if [[ "$gw" == link#* ]]; then
      /sbin/route -n delete -inet6 default -ifscope "$tun" >/dev/null 2>&1 || break
    else
      /sbin/route -n delete -inet6 default "$gw" >/dev/null 2>&1 || break
    fi
    removed6=$((removed6 + 1))
  done

  if [[ "$removed4" -gt 0 || "$removed6" -gt 0 ]]; then
    log_msg "Removed tunnel default routes on $tun (ipv4=$removed4 ipv6=$removed6)"
  fi
}

remove_dynamic_vpn_dns_state() {
  local tun
  tun="${TUNDEV:-}"
  [[ -z "$tun" ]] && return

  /usr/sbin/scutil >/dev/null 2>&1 <<-SCUTIL
    open
    remove State:/Network/Service/$tun/IPv4
    remove State:/Network/Service/$tun/DNS
    close
SCUTIL

  /usr/bin/dscacheutil -flushcache >/dev/null 2>&1 || true
  /usr/bin/killall -HUP mDNSResponder >/dev/null 2>&1 || true
  log_msg "Removed dynamic DNS/IPv4 state for $tun"
}

remove_legacy_gt_resolvers() {
  local domain file
  for domain in $GT_SCOPED_RESOLVER_DOMAINS; do
    file="/etc/resolver/$domain"
    if [[ -f "$file" ]]; then
      /bin/rm -f "$file"
      log_msg "Removed legacy scoped resolver $file"
    fi
  done
}

filter_split_default_routes() {
  local old_count new_count old6_count new6_count
  local i addr mask masklen
  local addr_var mask_var masklen_var proto_var sport_var dport_var

  export CISCO_IPV6_SPLIT_INC=0
  log_msg "Forced IPv6 split route count to 0"

  if [[ "${CISCO_SPLIT_INC:-}" =~ ^[0-9]+$ ]]; then
    old_count="$CISCO_SPLIT_INC"
    new_count=0

    for ((i = 0; i < old_count; i++)); do
      addr_var="CISCO_SPLIT_INC_${i}_ADDR"
      mask_var="CISCO_SPLIT_INC_${i}_MASK"
      masklen_var="CISCO_SPLIT_INC_${i}_MASKLEN"
      proto_var="CISCO_SPLIT_INC_${i}_PROTOCOL"
      sport_var="CISCO_SPLIT_INC_${i}_SPORT"
      dport_var="CISCO_SPLIT_INC_${i}_DPORT"

      addr="${!addr_var:-}"
      mask="${!mask_var:-}"
      masklen="${!masklen_var:-}"

      if [[ "$addr" == "0.0.0.0" && ( "$mask" == "0.0.0.0" || "$masklen" == "0" ) ]]; then
        continue
      fi

      export "CISCO_SPLIT_INC_${new_count}_ADDR=$addr"
      [[ -n "$mask" ]] && export "CISCO_SPLIT_INC_${new_count}_MASK=$mask"
      [[ -n "$masklen" ]] && export "CISCO_SPLIT_INC_${new_count}_MASKLEN=$masklen"
      [[ -n "${!proto_var:-}" ]] && export "CISCO_SPLIT_INC_${new_count}_PROTOCOL=${!proto_var}"
      [[ -n "${!sport_var:-}" ]] && export "CISCO_SPLIT_INC_${new_count}_SPORT=${!sport_var}"
      [[ -n "${!dport_var:-}" ]] && export "CISCO_SPLIT_INC_${new_count}_DPORT=${!dport_var}"
      new_count=$((new_count + 1))
    done

    export CISCO_SPLIT_INC="$new_count"
    log_msg "Filtered IPv4 split routes: $old_count -> $new_count"
  fi

  if [[ "${CISCO_IPV6_SPLIT_INC:-}" =~ ^[0-9]+$ ]]; then
    old6_count="$CISCO_IPV6_SPLIT_INC"
    new6_count=0

    for ((i = 0; i < old6_count; i++)); do
      addr_var="CISCO_IPV6_SPLIT_INC_${i}_ADDR"
      masklen_var="CISCO_IPV6_SPLIT_INC_${i}_MASKLEN"
      addr="${!addr_var:-}"
      masklen="${!masklen_var:-}"

      if [[ "$addr" == "::" && "$masklen" == "0" ]]; then
        continue
      fi

      export "CISCO_IPV6_SPLIT_INC_${new6_count}_ADDR=$addr"
      [[ -n "$masklen" ]] && export "CISCO_IPV6_SPLIT_INC_${new6_count}_MASKLEN=$masklen"
      new6_count=$((new6_count + 1))
    done

    export CISCO_IPV6_SPLIT_INC="$new6_count"
    log_msg "Filtered IPv6 split routes: $old6_count -> $new6_count"
  fi
}

if [[ ! -x "$REAL_VPNC_SCRIPT" ]]; then
  log_msg "Missing vpnc-script at $REAL_VPNC_SCRIPT"
  exit 1
fi

if [[ "${reason:-}" == "connect" || "${reason:-}" == "reconnect" ]]; then
  export CISCO_DEF_DOMAIN=""
  export CISCO_SPLIT_DNS=""
  ensure_vpnc_resolv_backup
  filter_split_default_routes
fi

"$REAL_VPNC_SCRIPT" "$@"
rc=$?

case "${reason:-}" in
  connect|reconnect)
    remove_tunnel_default_routes
    restore_primary_dns_to_dhcp
    remove_dynamic_vpn_dns_state
    remove_legacy_gt_resolvers
    add_gt_routes
    normalize_resolv_conf
    ;;
  disconnect)
    remove_gt_routes
    remove_dynamic_vpn_dns_state
    restore_primary_dns_to_dhcp
    remove_legacy_gt_resolvers
    normalize_resolv_conf
    ;;
esac

exit "$rc"
